version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember",
    "angular",
    "angularjs",
    "meteor"
  ]

[[transformers]]
name = "google-java-format"
enabled = true

[[transformers]]
name = "yapf"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "black"
enabled = true
